language: php
php:
  - '7.1'
matrix:
  fast_finish: true
sudo: false
before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
script:
  - mkdir storage/uploads storage/test
  - touch storage/test/acceptance.sqlite
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate --seed
  - vendor/bin/phpunit
